version: '3.7'

name: spring-boot-task

services:
  db:
    image: postgres:14
    container_name: task-db
    env_file: 
      - ./.env
    ports:
      - "5432:5432"
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file: 
      - ./.env
    ports:
      - "5050:80"

  java-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-app
    env_file: 
      - ./.env
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: >
      bash -c "mvn clean install && mvn spring-boot:run"
